name: Update

on:
  workflow_dispatch:
  schedule:
    - cron: '15 16 * * *'
    - cron: '35 18-23 * * 3'
    - cron: '35 0-12 * * 4'
    - cron: '*/5 13-15 * * 4'
    - cron: '35 0-12,18-23 11-31 12 *'
    - cron: '*/5 13-15 11-31 12 *'
    - cron: '35 0-12,18-23 1-6 1 *'
    - cron: '*/5 13-15 1-6 1 *'

jobs:
  scheduled:

    runs-on: ubuntu-latest

    steps:

    - name: Checkout
      uses: actions/checkout@v4
      with:
        ref: "data"

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.11"

    - name: Install dependencies
      run: |
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

    - name: Git Config
      run: |
        git config user.name woctezuma && git config user.email woctezuma@users.noreply.github.com

    - name: Run Updater
      run: |
        ./update.sh
      env:
        DISCORD_GIFT: ${{ secrets.DISCORD_GIFT }}
        DISCORD_WRAPPING: ${{ secrets.DISCORD_WRAPPING }}
